# Generated by Django 4.2.5 on 2023-10-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='strength',
            field=models.CharField(max_length=50),
        ),
    ]
