# Generated by Django 4.2.5 on 2023-10-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_alter_credential_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='strength',
        ),
        migrations.AddField(
            model_name='credential',
            name='website_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
