# Generated by Django 4.2.5 on 2023-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_remove_credential_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='session_token',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
