# Generated by Django 4.2.5 on 2023-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_myuser_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='session_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
