# Generated by Django 4.2.5 on 2023-11-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_alter_myuser_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='hashed_pin',
            field=models.BinaryField(),
        ),
    ]
