# Generated by Django 4.2.5 on 2023-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_alter_myuser_hashed_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
